Created delete /tweets/:id
corradodiba/unict pull request #10
Opened 2020-05-31 16:03 UTC by GlitchXCIV

2020-05-31 16:22 UTC, dandelionsam commented on test/tweets.spec.js
> +  it('should return 404 status if user don\'t exists', async () => {
```suggestion
  it('should return 404 status if tweet don\'t exists', async () => {
```

2020-05-31 16:22 UTC, dandelionsam commented on test/tweets.spec.js
> +describe('[DELETE] DELETE: /tweets/:id', () => {
```suggestion
describe('DELETE: /tweets/:id', () => {
```

2020-05-31 16:26 UTC, dandelionsam commented on test/tweets.spec.js
> +        .delete(`/users/${newObjectId}`);
```suggestion
    const result = await chai.request(app).delete(`/tweets/${newObjectId}`);
```

2020-06-01 08:02 UTC, corradodiba requested changes
Effettua un pull, di seguito assicurati di importare le seguenti librerie:
`const chai = require("chai");
const chaiHttp = require("chai-http");
const { createTweet } = require("./utils/createTweet");
const app = require("../app");
const { expect } = chai;
const mongoose = require("mongoose");
const { fakeLogin } = require("./utils/fakeLogin");
const User = require("../models/user");`

Applica i suggerimenti richiesti

2020-06-01 08:02 UTC, corradodiba commented on test/users.spec.js
> +});
Da rimuovere tutto, non fa parte di questa feature

2020-06-01 08:02 UTC, corradodiba commented on test/tweets.spec.js
> +    let createdTweet = undefined;
```suggestion
    const password = "dummypassword@1";
    let token = undefined;
    let createdTweet = undefined;
    let user = undefined;
```

2020-06-01 08:02 UTC, corradodiba commented on test/tweets.spec.js
> +    });
```suggestion
    before('create tweet', async () => {
      user = await User.create({
        email: "test@test.it",
        password,
        name: "Giusy",
        surname: "Giangravè",
      });
      createdTweet = await createTweet(user._id.toString());
      const { accessToken } = await fakeLogin(user.email, password);
      token = accessToken;
    });
```

2020-06-01 08:02 UTC, corradodiba commented on test/tweets.spec.js
> +    });
```suggestion
    after('delete tweet', () => {
      createdTweet ? createdTweet.remove() : console.log("missing tweet");
      user ? user.remove() : console.log("missing user");
    });
```

2020-06-01 08:02 UTC, corradodiba commented on test/tweets.spec.js
> +      expect(result.body).to.be.deep.equals({message: 'Tweet deleted'})
```suggestion
      expect(result.body).to.be.deep.equals({message: 'Tweet successfully deleted'})
```

2020-06-01 08:02 UTC, corradodiba commented on test/tweets.spec.js
> +          .delete(`/tweets/${createdTweet._id.toString()}`);
```suggestion
          .delete(`/tweets/${createdTweet._id.toString()}`)
          .set("authorization", `Bearer ${token}`);
```

2020-06-01 09:18 UTC, corradodiba approved these changes
LGTM

2020-06-01 09:18 UTC, merged