Feature/test/tweets
corradodiba/unict pull request #6
Opened 2020-05-30 16:29 UTC by davideturzo

2020-05-30 16:57 UTC, dandelionsam requested changes

2020-05-30 16:57 UTC, dandelionsam commented on test/tweets.spec.js
> +describe("GET: /users", () => {
Presidente, mi scusi l'inottemperanza, ma visto che il file è `tweets.spec.js`, nel primo argomento del describe, proporrei di mettere la stringa `"GET: /tweets"`, invece di quella attuale.

2020-05-30 16:59 UTC, davideturzo commented on test/tweets.spec.js
> +describe("GET: /users", () => {
Accetto il suo consiglio, mi riservo però di abbassarle lo stipendio. Il presidente non può mai essere corretto

2020-05-31 07:34 UTC, corradodiba commented on test/tweets.spec.js
> +describe("GET: /users", () => {
@davideturzo @dandelionsam ho sistemato io

2020-05-31 07:34 UTC, merged